export default defineEventHandler(() => {
  return [
    {
      id: "1",
      teamA: "Flash Kh",
      teamB: "See You Soon",
      img: "https://i.ytimg.com/vi/F-qxZr2Loi4/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLBrzVHwcT0F6UvfscLSmmeQt8wfog",
      title: "Match 1",
      live: true,
    },
    {
      id: "2",
      teamA: "CFU Gaming",
      teamB: "Galaxy Legends",
      img: "https://i.ytimg.com/vi/QUCFHlMswFU/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLDfBcWLcGcNvQ0Myo2yzB0RDB-MGA",
      title: "Match 2",
      button: "noti",
    },
    {
      id: "3",
      teamA: "Team Max",
      teamB: "Pro Esports",
      img: "https://i.ytimg.com/vi/wzSDhzPcDNU/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLC056IVASzSq6Bfj4oVZCvuiuiCvA",
      title: "Match 3",
      button: "mute",
    },
    {
      id: "4",
      teamA: "Team TDN",
      teamB: "Valhalla",
      img: "https://i.ytimg.com/vi/_61MbAYFxY0/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLAgS6E1pae4HqWvWruKkaTzmUtAJA",
      title: "Match 4",
      live: true,
    },
    {
      id: "5",
      teamA: "Flash Kh",
      teamB: "Team Max",
      img: "https://i.ytimg.com/vi/pBbT0JE1tn8/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLDQd4T3wFQ-cySdFnJDBjQBHQedrQ",
      title: "Match 4",
      live: true,
    },
    {
      id: "6",
      teamA: "See You Soon",
      teamB: "Team SV",
      img: "https://i.ytimg.com/vi/Kp3nSq6lFQI/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLBE6DTZfBdTn8Omyov3m__sdTr5UA",
      title: "Match 4",
      live: true,
    },
    {
      id: "7",
      teamA: "Logic Esports",
      teamB: "Team TDN",
      img: "https://i.ytimg.com/vi/wkaaHdcokPk/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLDu5qte9AzHQZFhCHskBIDkIJWlAw",
      title: "Match 4",
      live: true,
    },
    {
      id: "8",
      teamA: "Virtus.Pro",
      teamB: "CFU Gaming",
      img: "https://i.ytimg.com/vi/2obb7cnBOW4/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLBygo82qnC--5sxylUhQ7sL1At3Ag",
      title: "Match 4",
      live: true,
    },
  ];
});
